version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "boost_my_vocabulary"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  pgdata: