# Generated by Django 4.0.5 on 2022-06-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dictionary',
            table='dictionary',
        ),
    ]
