# Generated by Django 4.0.5 on 2022-06-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_word'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='word',
            table='word',
        ),
    ]
