# Generated by Django 4.0.5 on 2022-06-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_word_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='language',
            new_name='dictionary',
        ),
    ]
