# Generated by Django 4.0.5 on 2022-06-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_language_word_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
