# Generated by Django 3.2.9 on 2022-06-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220628_1545'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
