# Generated by Django 3.2.9 on 2022-07-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_profile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
