# Generated by Django 3.2.9 on 2022-07-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220701_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
